
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[238] =
    {   0,
        0,    0,   78,   77,   77,   77,   66,   77,   77,    5,
        4,   64,    2,   50,    3,    1,   65,   73,   52,   49,
       60,   55,   59,   75,   76,   75,   75,   75,   75,   75,
       75,   75,   75,   18,   75,   75,   75,   75,   75,   29,
       56,   57,   67,   77,   77,   63,    0,   69,    0,   71,
        0,   53,   51,    0,   73,    0,   48,   62,   58,   61,
       75,   75,   75,   75,   76,   76,   76,   75,   75,   37,
       75,    0,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   17,   75,   75,   75,   23,
       75,   75,   75,   75,   75,   54,    0,    0,   70,   68,

       72,   71,   74,    0,   73,   75,   75,   76,   75,   75,
       75,   38,   39,   42,   40,   75,   75,   75,   75,   75,
       75,    7,   75,   75,   75,   75,   75,   75,   75,   16,
       75,   75,   21,   22,   75,   75,   75,   27,   75,   70,
        0,   74,   75,   75,   76,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       11,   75,   75,   75,   19,   20,   75,   25,   75,   75,
       75,   75,   76,   75,   75,   35,   75,   75,   75,   75,
       45,   75,   75,   75,    6,    8,   75,   75,   12,   13,
       75,   24,   26,   75,   30,   75,   76,   33,   75,   75,

       41,   75,   75,   46,   75,   75,    9,   75,   75,   75,
       75,   76,   75,   75,   43,   75,   75,   75,   10,   75,
       75,   75,   32,   34,   75,   75,   47,   75,   14,   75,
       31,   36,   75,   15,   28,   44,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       31,   37,   38,   39,   40,   41,   31,   31,   42,   31,
       43,    1,   44,   45,    1,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   31,   31,   55,   56,   57,
       58,   59,   31,   60,   61,   62,   63,   64,   31,   31,
       65,   31,   66,   67,   68,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[243] =
    {   0,
        0,    0,  621,  622,  600,    0,  622,  613,   62,  622,
      622,  622,  622,  622,  597,  603,  622,   56,  596,  622,
      595,  594,  593,   55,   57,   58,   59,   68,  110,  596,
       72,   65,   62,  595,   83,   85,  106,  137,  159,  594,
      565,  622,  622,   71,  541,  622,  603,  622,   83,  622,
      123,  622,  622,  590,  128,  101,  622,  622,  622,  622,
      589,  581,  117,  152,  578,  577,  105,  139,  163,  129,
      146,   70,  168,  166,  173,  176,  187,  179,  196,  197,
      190,  206,  195,  216,  213,  576,  186,  218,  233,  575,
      232,  199,  237,  220,  238,  622,  203,  229,  622,  622,

      622,  179,  251,  111,  574,  252,  254,  258,  260,  256,
      265,  573,  571,  622,  267,  268,  271,  284,  291,  269,
      278,  570,  275,  292,  298,  305,  304,  308,  315,  569,
      313,  320,  567,  566,  321,  323,  324,  565,  339,  318,
      344,  564,  327,  329,  345,  334,  353,  328,  357,  347,
      362,  364,  367,  358,  381,  366,  382,  377,  378,  387,
      563,  390,  392,  393,  562,  561,  399,  560,  402,  414,
      397,  404,  421,  424,  410,  559,  423,  426,  428,  431,
      554,  435,  436,  437,  553,  552,  443,  440,  551,  550,
      446,  543,  541,  453,  540,  448,  461,  539,  455,  463,

      538,  466,  477,  536,  457,  472,  530,  478,  492,  495,
      480,  469,  500,  503,  528,  485,  506,  512,  289,  501,
      504,  513,  247,  245,  514,  517,  243,  527,  180,  526,
      141,  131,  537,   96,   91,   80,  622,  595,  598,   88,
       73,  601
    } ;

static const flex_int16_t yy_def[243] =
    {   0,
      237,    1,  237,  237,  237,  238,  237,  237,  239,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  240,  241,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      237,  237,  237,  242,  237,  237,  237,  237,  239,  237,
      239,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      240,  240,  240,  240,  241,  241,  241,  240,  240,  240,
      240,  237,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  237,  242,  242,  237,  237,

      237,  239,  237,  237,  237,  240,  240,  241,  240,  240,
      240,  240,  240,  237,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  242,
      237,  237,  240,  240,  241,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  241,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  241,  240,  240,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  241,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  241,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,    0,  237,  237,  237,
      237,  237
    } ;

static const flex_int16_t yy_nxt[691] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   30,
       30,   30,   32,   33,   34,   35,   36,   37,   38,   30,
       39,   40,   41,   42,   43,   24,   25,   26,   27,   28,
       29,   30,   31,   30,   30,   32,   33,   34,   35,   36,
       37,   38,   30,   39,   40,   44,   45,    4,   50,   54,
       61,   55,   65,   61,   61,   66,   51,   61,   63,   68,
       61,   56,   72,   61,   70,   98,   64,   61,   71,   50,
       62,   67,   69,   83,   84,   61,   86,   51,   61,   85,

       61,   73,   63,   68,   87,   56,   61,  114,   70,   64,
       88,   61,   71,  104,   67,   69,  105,   83,   84,   86,
       65,   61,   85,  104,   73,   61,  142,   89,   87,  102,
      114,   74,   61,   75,   88,   90,   76,   51,   99,  108,
      106,   54,   77,   55,   61,   78,   61,   79,   80,   81,
       82,   89,   61,   56,   61,   74,   61,   75,   91,   90,
       76,   61,  108,  109,  106,   77,   92,   61,   78,  112,
       79,   80,   81,   82,   61,  110,   93,   56,   61,  107,
       94,   61,   91,   61,   95,   50,  113,  109,   61,  116,
       92,   61,  112,   51,   61,   61,  111,  117,  110,   93,

      121,   61,   61,  107,   94,   61,  115,  118,   95,  113,
       61,   61,   61,  116,   61,  119,  120,   98,  127,  111,
      117,   61,  131,  125,  121,  122,  123,  126,   61,  115,
      118,   61,  128,   61,  136,   61,  124,  130,  119,  132,
      120,  129,  127,   98,  133,  131,  125,   61,   61,  122,
      123,  126,   61,   61,  135,  128,  138,  136,   61,  124,
       61,  130,   65,  132,  134,  129,  103,   61,  133,   61,
       99,   61,  137,   65,  139,   61,  141,  147,  135,  138,
       61,  143,   61,   61,   61,  146,   61,  134,  144,  145,
       61,  151,  150,   61,  156,  137,  140,  139,  152,   61,

      141,  147,  148,  149,   61,  143,   61,   61,  153,  146,
      158,  144,  145,   61,  157,  151,  150,  154,  156,   61,
       61,  160,  152,   61,  155,  148,  149,  159,   61,  162,
       61,  153,   98,  158,  165,   61,   61,  157,   61,   61,
      154,  161,   61,   61,   61,  160,  163,  155,  164,   61,
      159,  166,  167,  162,   61,  169,  104,  168,  165,  142,
       65,  171,   61,  170,  161,  172,  176,  174,   61,  163,
      173,  164,   61,   61,  166,  167,  175,   61,  169,   61,
      168,   61,   61,  178,  171,   99,  177,  170,  172,  176,
      174,  179,   61,   61,  173,  182,   61,   61,  180,  184,

      175,  181,   61,  185,  183,   61,  178,   61,   61,  187,
      177,  186,   61,  190,   61,  179,  188,   61,  182,   61,
      192,  180,  184,  193,  181,   61,  189,  185,  183,   61,
      195,  191,  187,  196,  186,  194,   65,  190,   61,   61,
      188,   61,  197,   61,  192,  198,   61,  193,  199,  189,
       61,   61,   61,  195,  191,   61,  200,  196,   61,  194,
      201,   61,  202,   61,  207,  205,  197,  203,   61,  198,
       61,  199,   61,  204,  208,  206,   65,  210,   61,  200,
      213,   61,  209,  201,   65,  202,  211,   61,  207,  205,
      203,  217,   61,   61,  212,   61,  204,  208,  206,  215,

       61,  210,  214,  223,  213,  209,  216,   61,  218,  211,
       61,  219,  222,  220,  217,   61,   61,  212,   61,   61,
      221,   61,  215,  226,  225,  214,  223,   61,   61,   61,
      216,  218,   61,  228,  219,  222,  224,  220,  229,  227,
      230,   61,   61,   61,  221,   61,  226,  231,  225,  233,
      232,   61,   61,   61,   61,   61,   61,  228,   61,  224,
      235,  229,  227,  230,  234,   61,   61,   61,   61,   61,
      231,  236,  233,  232,   61,   61,   61,   61,   61,  142,
       61,   61,   61,  235,   61,   61,   61,  234,   61,  105,
       61,   61,   65,   65,  236,   47,   61,   47,   49,   49,

       49,   97,   97,   97,   61,  103,  101,  100,   96,   61,
       61,   61,   60,   59,   58,   57,   53,   52,   48,   46,
      237,    3,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237
    } ;

static const flex_int16_t yy_chk[691] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   18,
       24,   18,   25,   26,   27,  241,    9,   33,   24,   26,
       32,   18,   28,   28,   27,   44,   24,   31,   27,   49,
      240,   25,   26,   31,   32,  236,   33,   49,   35,   32,

       36,   28,   24,   26,   35,   18,  235,   72,   27,   24,
       36,  234,   27,   56,   25,   26,   56,   31,   32,   33,
       67,   37,   32,  104,   28,   29,  104,   37,   35,   51,
       72,   29,   63,   29,   36,   37,   29,   51,   44,   67,
       63,   55,   29,   55,   70,   29,  232,   29,   29,   29,
       29,   37,   38,   55,   68,   29,  231,   29,   38,   37,
       29,   71,   67,   68,   63,   29,   38,   64,   29,   70,
       29,   29,   29,   29,   39,   68,   38,   55,   69,   64,
       39,   74,   38,   73,   39,  102,   71,   68,   75,   74,
       38,   76,   70,  102,   78,  229,   69,   74,   68,   38,

       78,   87,   77,   64,   39,   81,   73,   75,   39,   71,
       83,   79,   80,   74,   92,   76,   77,   97,   83,   69,
       74,   82,   87,   81,   78,   79,   80,   82,   85,   73,
       75,   84,   83,   88,   92,   94,   80,   85,   76,   88,
       77,   84,   83,   98,   88,   87,   81,   91,   89,   79,
       80,   82,   93,   95,   91,   83,   94,   92,  227,   80,
      224,   85,  223,   88,   89,   84,  103,  106,   88,  107,
       97,  110,   93,  108,   95,  109,  103,  110,   91,   94,
      111,  106,  115,  116,  120,  109,  117,   89,  107,  108,
      123,  116,  115,  121,  120,   93,   98,   95,  117,  118,

      103,  110,  111,  111,  219,  106,  119,  124,  117,  109,
      123,  107,  108,  125,  121,  116,  115,  118,  120,  127,
      126,  125,  117,  128,  119,  111,  111,  124,  131,  127,
      129,  117,  140,  123,  131,  132,  135,  121,  136,  137,
      118,  126,  143,  148,  144,  125,  128,  119,  129,  146,
      124,  132,  135,  127,  139,  137,  141,  136,  131,  141,
      145,  143,  150,  139,  126,  144,  148,  146,  147,  128,
      145,  129,  149,  154,  132,  135,  147,  151,  137,  152,
      136,  156,  153,  150,  143,  140,  149,  139,  144,  148,
      146,  151,  158,  159,  145,  154,  155,  157,  152,  156,

      147,  153,  160,  157,  155,  162,  150,  163,  164,  159,
      149,  158,  171,  163,  167,  151,  160,  169,  154,  172,
      167,  152,  156,  169,  153,  175,  162,  157,  155,  170,
      171,  164,  159,  172,  158,  170,  173,  163,  177,  174,
      160,  178,  173,  179,  167,  174,  180,  169,  175,  162,
      182,  183,  184,  171,  164,  188,  177,  172,  187,  170,
      178,  191,  179,  196,  187,  183,  173,  180,  194,  174,
      199,  175,  205,  182,  188,  184,  197,  194,  200,  177,
      199,  202,  191,  178,  212,  179,  196,  206,  187,  183,
      180,  205,  203,  208,  197,  211,  182,  188,  184,  202,

      216,  194,  200,  212,  199,  191,  203,  209,  206,  196,
      210,  208,  211,  209,  205,  213,  220,  197,  214,  221,
      210,  217,  202,  216,  214,  200,  212,  218,  222,  225,
      203,  206,  226,  218,  208,  211,  213,  209,  220,  217,
      221,  230,  228,  215,  210,  207,  216,  222,  214,  226,
      225,  204,  233,  201,  198,  195,  193,  218,  192,  213,
      230,  220,  217,  221,  228,  190,  189,  186,  185,  181,
      222,  233,  226,  225,  176,  168,  166,  165,  161,  142,
      138,  134,  133,  230,  130,  122,  113,  228,  112,  105,
       90,   86,   66,   65,  233,  238,   62,  238,  239,  239,

      239,  242,  242,  242,   61,   54,   47,   45,   41,   40,
       34,   30,   23,   22,   21,   19,   16,   15,    8,    5,
        3,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
/* scanner for a toy Pascal-like language */
#line 4 "flex.l"
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include "y.tab.h"

int deCadenaAEntero(char* cadena);

double deCadenaAFloat(char* cadena);
#line 682 "lex.yy.c"
/* Definiciones basicas */
/*Literales enteros*/
/*Literales reales*/
/*Literal cadena*/
/*Literal caracter*/
/*Comentarios*/
#line 689 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 113 "flex.l"

#line 908 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 238 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 622 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 114 "flex.l"
{printf("Se ha leido %s\n",yytext); yylval.valor_texto = strdup(yytext); return (BPUNTO);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 115 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BSUMA);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 116 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BMENOS);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 117 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BPARENTESIS_CIERRE);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BPARENTESIS_APERTURA);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 119 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BPARA);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 120 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFSI);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFTIPO);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 122 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFTUPLA);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 123 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFUNCION);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 124 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFVAR);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 125 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BHACER);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 126 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BHASTA);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 127 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BMIENTRAS);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 128 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFMIENTRAS);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 129 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BMOD);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 130 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BNO);};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 131 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BO);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 132 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BPARA);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 133 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTIPO_BASE);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 134 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BREF);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 135 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BSAL);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 136 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BSI);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 137 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTABLA);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 138 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTIPO);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 139 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTUPLA);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 140 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BVAR);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 141 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BVERDADERO);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 142 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BY);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 143 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BACCION);} 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 144 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BALGORITMO);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTIPO_BASE);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTIPO_BASE);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTIPO_BASE);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 148 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BCONST);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BCONTINUAR);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 150 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BDE);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 151 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BDEV);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 152 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BDIV);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BENT);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 154 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BTIPO_BASE);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 155 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BES);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 156 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFACCION);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 157 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFALGORITMO);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 158 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFALSO);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 159 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFCONST);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 160 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BFFUNCION);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 161 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BDOS_PUNTOS_IGUAL);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 162 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BPUNTO_Y_COMA);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 163 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BCOMA);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BPUNTOSS);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 165 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BDOS_PUNTOS);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 166 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BENTONCES);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 167 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BSINO);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 168 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BIGUAL);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 169 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BCORCHETE_APERTURA);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 170 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BCORCHETE_CIERRE);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 171 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BIGUAL);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 172 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BOPREL);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 173 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BOPREL);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 174 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BOPREL);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 175 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BOPREL);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 176 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BOPREL);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 177 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BPOR);} 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 178 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BDIV);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 179 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BMOD);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 180 "flex.l"
{printf("Se ha leido %s\n",yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 181 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BO);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 182 "flex.l"
{printf("Se ha leido %s\n",yytext);yylval.valor_texto = strdup(yytext);return (BY);}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 187 "flex.l"
{printf("Se ha leido un comentario %s\n", yytext);yylval.valor_texto = strdup(yytext); return (BCOMENTARIO);}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 189 "flex.l"
{printf("Se ha leido una cadena %s\n", yytext); yylval.valor_texto = strdup(yytext); return (BLITERAL_CADENA); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 191 "flex.l"
{printf("Se ha leido un caracter %s\n", yytext );yylval.valor_texto = strdup(yytext); return (BLITERAL_CARACTER);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 193 "flex.l"
{printf("Se ha leido un literal entero con valor %d\n", deCadenaAEntero(yytext)); yylval.valor_doble = deCadenaAEntero(yytext); return (BLITERAL_NUMERICO);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 195 "flex.l"
{printf("Se ha leido un literal real con valor %f\n", deCadenaAFloat(yytext)); yylval.valor_doble = deCadenaAFloat(yytext); return (BLITERAL_NUMERICO);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 197 "flex.l"
{printf("Se ha leido un identificador\n"); yylval.valor_texto = strdup(yytext);return BIDENTIFICADOR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 198 "flex.l"
{printf("Se ha leido un identificador booleano\n"); yylval.valor_texto = strdup(yytext);return (BIDENTIFICADORB);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 202 "flex.l"
ECHO;
	YY_BREAK
#line 1352 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 238 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 238 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 237);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 202 "flex.l"


int deCadenaAEntero(char* cadena){
	int multiplicador = 1;
	if (*cadena=='+'){
		cadena = &cadena[1];
	}else{
		if (*cadena=='-'){
			multiplicador = -1;
			cadena = &cadena[1];
		}
	}
	char *token1 = strtok(cadena, "e");
	char *token2 = strtok(NULL,"e");
	if (token2 == NULL){
		char *token3 = strtok(token1, "E");
		char *token4 = strtok(NULL,"E");

		token1 = token3;

		if (token4 != NULL){

			for (int i=0; i<atoi(token4); i++){
				multiplicador = multiplicador * 10;
			}

		}
		
	}else{

		for (int i=0; i<atoi(token2); i++){
			multiplicador = multiplicador * 10;
		}
	
	}


	int dev = atoi(token1)*multiplicador;

	return dev;


}

double deCadenaAFloat(char* cadena){

	int numero;
	double multiplicador = 1;
	double aux;
	if (*cadena=='+'){
		cadena = &cadena[1];
	}else{
		if (*cadena=='-'){
			multiplicador = -1;
			cadena = &cadena[1];
		}
	}
	char *token1 = strtok(cadena, "e");
	char *token2 = strtok(NULL,"e");
	if (token2 == NULL){
		char *token3 = strtok(token1, "E");
		char *token4 = strtok(NULL,"E");
		
		token1 = token3;

		if (token4 != NULL){

			
			if (*token4=='-'){
				aux=0.1;
				numero = - atoi(token4);

			}else{
				aux=10;
				numero = atoi(token4);
			}

			for (int i=0; i<numero; i++){
				multiplicador = multiplicador * aux;
			}

		}
		
	}else{

		if (*token2=='-'){
			aux=0.1;
			numero = - atoi(token2);

		}else{
			aux=10;
			numero = atoi(token2);
		}

		for (int i=0; i<numero; i++){
			multiplicador = multiplicador * aux;
		}
	
	}
	
	double dev = atof(token1)*multiplicador;

	return dev;


}

/*
int main( int argc, char **argv ){
	++argv, --argc;
	if ( argc > 0 )
		scanf("", &yyin);
	else
		yyin = stdin;

	yylex();
}
*/
